In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.preprocessing import LabelEncoder

# load dataset
dataframe = pd.read_csv("type3.csv")


In [2]:
corpus = dataframe['content'].tolist()
corpus

['情報 TOYOTA 女神 張景嵐 ALTIS 試駕會 ALTIS HYBRID 上市 張景嵐 不錯 哈哈哈 報名 連結 y2vycnhq 按摩 住宿 簽名 禮物 沒事 一起 報名 給它 抽起來 TOYOTATAIWAN Facebook 發起 拍照 投稿 活動 複雜 獎品 不錯 研究 貼文 活動 網址 758329298268878nan',
 'Toyota Altis 燃油泵 召回 紀錄 沒想到 中獎 施工 整個 過程 小時 更換 第一次 發動 發動 不順 順便 20000 公里 例行 保養 保養 上工 亮點 昏倒 我還 沒收 通知單 昨天 萬定 原廠 順便 處裡 下次 再花 一趟 更換 燃油泵 更換 汽油 更換 有否 差異 怠速 抖動 有否 改善 汽油 低點 去換 免得 全車 汽油味 燃油泵 類型 一種 內含 濾蕊 召回 賺到 一種 濾蕊 在外 里程 里程 數高 著換會 省工',
 '這才 負責 第一名 失望 自主 安全性 召回 敲門 Altis Camry Alphard Prado 貼心 主動 來函 通知 預約 順利 放鬆 心情 喝咖啡 對象 國產 Altis Camry 進口 Alphard Prado 葉片 卡住 症候群 失速 加速 爆衝 回廠 磨損 該換 輪胎 磨損 更換 個奈米 空氣 濾清器 業績 達標 一堆 酸酸 可憐 哪連 過都 召回 反觀 車廠 碟盤 上次 生鏽 提早 安全性 更換 輪胎 吃邊 一起 技師 電池壽命 導航系統 更新 很貴要 800 放棄 召回 期限 收到 通知書 字面上 解釋 熄火 泵浦 燃油 導致 斷油 抖動 最終 引擎 熄火 引擎 熄火 動力 煞車 失去 功能 方向盤 轉動 放鬆 心情 喝咖啡 喜歡 維修保養 喝咖啡 碟盤 上次 生鏽 提早 安全性 更換 泰有 真是太 美好 每個 機會 換碟 尤其 梅雨季節 一個月 幾次 版上 搜尋 碟盤 生鏽 車迷 車廠 感恩戴德 碟盤 生鏽 山路 一趟 亮晶晶 一輪 邊換 四輪 更新 程式 800 嫌貴 反串 召回 還能 凹成 大廠 負責 信仰 好好 願意 回廠 重點 拆裝 好好 拆過 更換 燃油 濾清器 重點 拆裝 好好 拆過 想酸 挑個 大牙 表示 供神 太棒了 碟盤 生鏽 下班 回家 下雨 隔天 早上 出門 上班 時碟盤 30 分鐘 閃亮 梅雨季 幾次 碟盤 口袋 超級 羨慕

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()

In [4]:
Y = dataframe['type'].tolist()
Y

['Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis',
 'Toyota_Altis

In [5]:
# encode class values as integers
encoder = LabelEncoder()
encoded_Y = encoder.fit_transform(Y)
# convert integers to dummy variables (one hot encoding)
dummy_y = np_utils.to_categorical(encoded_Y)
dummy_y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

In [18]:
from keras.models import Sequential
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.layers.core import Activation
from keras.layers.core import Flatten
from keras.layers.core import Dense
from keras.layers.core import Dropout
from keras import backend as K
# define model structure
model = Sequential()
model.add(Dense(10, input_dim=1500, activation = 'relu'))
# model.add(Dense(output_dim=10, input_dim=1500, activation='relu'))
model.add(Dropout(0.2))
# model.add(Dense(output_dim=3, input_dim=10, activation='softmax'))
model.add(Dense(3, input_dim=10, activation='softmax'))
model.summary()


Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_11 (Dense)             (None, 10)                15010     
_________________________________________________________________
dropout_5 (Dropout)          (None, 10)                0         
_________________________________________________________________
dense_12 (Dense)             (None, 3)                 33        
Total params: 15,043
Trainable params: 15,043
Non-trainable params: 0
_________________________________________________________________


In [19]:
from keras.optimizers import Adam
# Compile model
EPOCHS = 40
INIT_LR = 1e-3
BS = 256
opt = Adam(lr=INIT_LR, decay=INIT_LR / EPOCHS)
model.compile(loss="categorical_crossentropy", optimizer=opt,
    metrics=["accuracy"])

In [21]:
# splitting data into training set and test set. If random_state is set to an integer, the split datasets are fixed.
X_train, X_test, Y_train, Y_test = train_test_split(X, dummy_y, test_size=0.3, random_state=0)


In [22]:
H = model.fit(x=X_train, y=Y_train, batch_size=BS, epochs=EPOCHS, verbose=1, validation_data=(X_test, Y_test))

Epoch 1/40
50/50 [==============================] - 1s 14ms/step - loss: 1.0010 - accuracy: 0.5973 - val_loss: 0.8474 - val_accuracy: 0.7196
Epoch 2/40
50/50 [==============================] - 0s 8ms/step - loss: 0.7693 - accuracy: 0.7463 - val_loss: 0.6997 - val_accuracy: 0.7956
Epoch 3/40
50/50 [==============================] - 0s 9ms/step - loss: 0.6180 - accuracy: 0.8273 - val_loss: 0.5842 - val_accuracy: 0.8688
Epoch 4/40
50/50 [==============================] - 0s 8ms/step - loss: 0.4992 - accuracy: 0.8723 - val_loss: 0.4998 - val_accuracy: 0.8927
Epoch 5/40
50/50 [==============================] - 0s 8ms/step - loss: 0.4119 - accuracy: 0.8972 - val_loss: 0.4399 - val_accuracy: 0.9088
Epoch 6/40
50/50 [==============================] - 0s 8ms/step - loss: 0.3524 - accuracy: 0.9152 - val_loss: 0.4075 - val_accuracy: 0.9134
Epoch 7/40
50/50 [==============================] - 0s 9ms/step - loss: 0.3075 - accuracy: 0.9240 - val_loss: 0.3848 - val_accuracy: 0.9251
Epoch 8/40
50/50 [=

In [42]:
scores = model.evaluate(X_test, Y_test, verbose=0)
scores
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

accuracy: 42.54%


In [67]:
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv1D, MaxPooling1D
from keras.layers.embeddings import Embedding
vocab_size = np.max([np.max(X_train[i]) for i in range(X_train.shape[0])]) + 1  # 这里1 代表空格，其索引被认为是0。
 
model = Sequential()
model.add(Embedding(vocab_size, 64, input_length=1500))
model.add(Conv1D(filters=64, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Dropout(0.25))
model.add(Conv1D(filters=128, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(3, activation='softmax'))
 
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
print(model.summary())
 


Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 1500, 64)          143168    
_________________________________________________________________
conv1d (Conv1D)              (None, 1500, 64)          12352     
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 750, 64)           0         
_________________________________________________________________
dropout_8 (Dropout)          (None, 750, 64)           0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 750, 128)          24704     
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 375, 128)          0         
_________________________________________________________________
dropout_9 (Dropout)          (None, 375, 128)        

In [69]:
model.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=20, batch_size=100)
scores = model.evaluate(X_test, Y_test, verbose=1)
print(scores)

Epoch 1/20
126/126 [==============================] - 98s 782ms/step - loss: 0.5508 - accuracy: 0.7767 - val_loss: 0.1741 - val_accuracy: 0.9405
Epoch 2/20
126/126 [==============================] - 105s 833ms/step - loss: 0.1404 - accuracy: 0.9491 - val_loss: 0.1615 - val_accuracy: 0.9390
Epoch 3/20
126/126 [==============================] - 115s 911ms/step - loss: 0.1047 - accuracy: 0.9619 - val_loss: 0.1311 - val_accuracy: 0.9483
Epoch 4/20
126/126 [==============================] - 105s 835ms/step - loss: 0.0807 - accuracy: 0.9681 - val_loss: 0.1603 - val_accuracy: 0.9451
Epoch 5/20
126/126 [==============================] - 119s 942ms/step - loss: 0.0696 - accuracy: 0.9745 - val_loss: 0.1354 - val_accuracy: 0.9511
Epoch 6/20
126/126 [==============================] - 132s 1s/step - loss: 0.0590 - accuracy: 0.9780 - val_loss: 0.1395 - val_accuracy: 0.9485
Epoch 7/20
126/126 [==============================] - 150s 1s/step - loss: 0.0552 - accuracy: 0.9797 - val_loss: 0.1517 - val_ac

NameError: name 'y_test' is not defined

In [70]:
scores = model.evaluate(X_test, Y_test, verbose=1)
print(scores)

169/169 [==============================] - 7s 44ms/step - loss: 0.1853 - accuracy: 0.9479
[0.18534953892230988, 0.947914719581604]


In [75]:
from keras.layers import Convolution1D, Flatten, Dropout, MaxPool1D, GlobalAveragePooling1D
from keras.layers import  BatchNormalization
model = Sequential()
model.add(Embedding(vocab_size, 300, input_length=1500))
model.add(Convolution1D(256, 3, padding='same'))
model.add(MaxPool1D(3,3,padding='same'))
model.add(Convolution1D(128, 3, padding='same'))
model.add(MaxPool1D(3,3,padding='same'))
model.add(Convolution1D(64, 3, padding='same'))
model.add(Flatten())
model.add(Dropout(0.1))
model.add(BatchNormalization()) # (批)规范化层
model.add(Dense(256,activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(3,activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
print(model.summary())


Model: "sequential_16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 1500, 300)         671100    
_________________________________________________________________
conv1d_5 (Conv1D)            (None, 1500, 256)         230656    
_________________________________________________________________
max_pooling1d_4 (MaxPooling1 (None, 500, 256)          0         
_________________________________________________________________
conv1d_6 (Conv1D)            (None, 500, 128)          98432     
_________________________________________________________________
max_pooling1d_5 (MaxPooling1 (None, 167, 128)          0         
_________________________________________________________________
conv1d_7 (Conv1D)            (None, 167, 64)           24640     
_________________________________________________________________
flatten_2 (Flatten)          (None, 10688)           

In [76]:
model.fit(X_train, Y_train,
          batch_size=32,
          epochs=15,
          validation_data=(X_test, Y_test))
scores = model.evaluate(X_test, Y_test, verbose=1)
print(scores)

Epoch 1/15
394/394 [==============================] - 676s 2s/step - loss: 0.5470 - accuracy: 0.8627 - val_loss: 1.5967 - val_accuracy: 0.7281
Epoch 2/15
394/394 [==============================] - 690s 2s/step - loss: 0.1931 - accuracy: 0.9310 - val_loss: 0.2541 - val_accuracy: 0.9260
Epoch 3/15
394/394 [==============================] - 690s 2s/step - loss: 0.1328 - accuracy: 0.9522 - val_loss: 0.2335 - val_accuracy: 0.9314
Epoch 4/15
394/394 [==============================] - 594s 2s/step - loss: 0.1177 - accuracy: 0.9562 - val_loss: 0.2087 - val_accuracy: 0.9383
Epoch 5/15
394/394 [==============================] - 599s 2s/step - loss: 0.1211 - accuracy: 0.9562 - val_loss: 0.6780 - val_accuracy: 0.8669
Epoch 6/15
394/394 [==============================] - 724s 2s/step - loss: 0.1040 - accuracy: 0.9615 - val_loss: 0.3607 - val_accuracy: 0.9262
Epoch 7/15
394/394 [==============================] - 760s 2s/step - loss: 0.0963 - accuracy: 0.9645 - val_loss: 0.7459 - val_accuracy: 0.8174

In [71]:
del model

In [50]:
# make predictions
pred = model.predict(X_test)
pred

array([[0.76135486, 0.10432221, 0.13432293],
       [0.35309   , 0.34079552, 0.30611446],
       [0.41093215, 0.38670924, 0.20235856],
       ...,
       [0.43094504, 0.25162974, 0.31742528],
       [0.3388412 , 0.32115078, 0.34000805],
       [0.21927346, 0.07264376, 0.70808274]], dtype=float32)

In [28]:
# inverse numeric variables to initial categorical labels
init_lables = encoder.inverse_transform(pred.flatten())

ValueError: y contains previously unseen labels: [1.2253048e-38 1.7947766e-38 2.1857589e-38 ... 9.9999964e-01 9.9999976e-01
 9.9999988e-01]

In [39]:
from sklearn.model_selection import StratifiedKFold
# k-fold cross-validate
seed = 42
np.random.seed(seed)
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
# results = cross_val_score(model, X, dummy_y, cv=kfold,)
cvscores = []
for train, test in kfold.split(X, dummy_y):
  # create model
    model = Sequential()
    model.add(Dense(10, input_dim=1500, activation = 'relu'))
    model.add(Dropout(0.2))
    model.add(Dense(3, input_dim=10, activation='softmax'))
    # Compile model
    model.compile(loss="categorical_crossentropy", optimizer='adam', metrics=['accuracy'])
    # Fit the model
    model.fit(X[train], dummy_y[train], epochs=150, batch_size=10, verbose=0)
    # evaluate the model
    scores = model.evaluate(X[test], dummy_y[test], verbose=0)
    print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
    cvscores.append(scores[1] * 100)
print("%.2f%% (+/- %.2f%%)" % (numpy.mean(cvscores), numpy.std(cvscores)))

ValueError: in user code:

    C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:533 train_step  **
        y, y_pred, sample_weight, regularization_losses=self.losses)
    C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\keras\engine\compile_utils.py:205 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\keras\losses.py:143 __call__
        losses = self.call(y_true, y_pred)
    C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\keras\losses.py:246 call
        return self.fn(y_true, y_pred, **self._fn_kwargs)
    C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\keras\losses.py:1527 categorical_crossentropy
        return K.categorical_crossentropy(y_true, y_pred, from_logits=from_logits)
    C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\keras\backend.py:4561 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\framework\tensor_shape.py:1117 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (None, 1) and (None, 3) are incompatible


In [47]:
for train, test in kfold.split(X, encoded_Y):
    print(encoded_Y[test])

[0 0 0 ... 1 1 1]
[0 0 0 ... 1 1 1]
[0 0 0 ... 1 1 1]
[0 0 0 ... 1 1 1]
[0 0 0 ... 1 1 1]
[0 0 0 ... 1 1 1]
[0 0 0 ... 1 1 1]
[0 0 0 ... 1 1 1]
[0 0 0 ... 1 1 1]
[0 0 0 ... 1 1 1]


In [77]:
scores = model.evaluate(X_test, Y_test, verbose=1)
print(scores)

169/169 [==============================] - 48s 284ms/step - loss: 0.2883 - accuracy: 0.9433
[0.2883286774158478, 0.943280816078186]


In [94]:
cv.transform(['Altis']).toarray()
cv.vocabulary_

{'toyota': 164,
 'altis': 92,
 'hybrid': 127,
 '上市': 212,
 '不錯': 251,
 '哈哈哈': 484,
 '連結': 1364,
 '沒事': 938,
 '一起': 196,
 '活動': 960,
 '研究': 1060,
 '召回': 461,
 '紀錄': 1104,
 '沒想到': 943,
 '整個': 831,
 '過程': 1378,
 '小時': 621,
 '更換': 875,
 '第一次': 1090,
 '發動': 1030,
 '順便': 1471,
 '公里': 384,
 '保養': 326,
 '我還': 734,
 '昨天': 861,
 '原廠': 451,
 '下次': 226,
 '汽油': 935,
 '差異': 640,
 '怠速': 705,
 '抖動': 756,
 '改善': 819,
 '全車': 368,
 '一種': 193,
 '里程': 1401,
 '負責': 1251,
 '安全性': 582,
 'camry': 98,
 '主動': 263,
 '通知': 1360,
 '心情': 698,
 '國產': 518,
 '進口': 1369,
 '加速': 429,
 '回廠': 507,
 '輪胎': 1336,
 '空氣': 1080,
 '業績': 903,
 '一堆': 187,
 '車廠': 1307,
 '上次': 213,
 '生鏽': 1017,
 '技師': 753,
 '更新': 876,
 '放棄': 827,
 '解釋': 1202,
 '熄火': 984,
 '導致': 618,
 '引擎': 668,
 '動力': 432,
 '煞車': 982,
 '功能': 421,
 '方向盤': 845,
 '喜歡': 493,
 '每個': 924,
 '機會': 911,
 '尤其': 624,
 '一個月': 184,
 '幾次': 658,
 '版上': 989,
 '搜尋': 802,
 '山路': 633,
 '四輪': 500,
 '還能': 1390,
 '好好': 570,
 '願意': 1479,
 '重點': 1406,
 '表示': 1187,
 '回家': 506,
 '早上': 855,
 '

In [91]:
import pickle
with open('feature.pkl', 'wb') as fw:
    pickle.dump(cv.vocabulary_, fw)

In [92]:
sc = CountVectorizer(vocabulary=pickle.load(open('feature.pkl', "rb")))

In [95]:
sc.transform(['Altis']).toarray()
sc.vocabulary_

{'toyota': 164,
 'altis': 92,
 'hybrid': 127,
 '上市': 212,
 '不錯': 251,
 '哈哈哈': 484,
 '連結': 1364,
 '沒事': 938,
 '一起': 196,
 '活動': 960,
 '研究': 1060,
 '召回': 461,
 '紀錄': 1104,
 '沒想到': 943,
 '整個': 831,
 '過程': 1378,
 '小時': 621,
 '更換': 875,
 '第一次': 1090,
 '發動': 1030,
 '順便': 1471,
 '公里': 384,
 '保養': 326,
 '我還': 734,
 '昨天': 861,
 '原廠': 451,
 '下次': 226,
 '汽油': 935,
 '差異': 640,
 '怠速': 705,
 '抖動': 756,
 '改善': 819,
 '全車': 368,
 '一種': 193,
 '里程': 1401,
 '負責': 1251,
 '安全性': 582,
 'camry': 98,
 '主動': 263,
 '通知': 1360,
 '心情': 698,
 '國產': 518,
 '進口': 1369,
 '加速': 429,
 '回廠': 507,
 '輪胎': 1336,
 '空氣': 1080,
 '業績': 903,
 '一堆': 187,
 '車廠': 1307,
 '上次': 213,
 '生鏽': 1017,
 '技師': 753,
 '更新': 876,
 '放棄': 827,
 '解釋': 1202,
 '熄火': 984,
 '導致': 618,
 '引擎': 668,
 '動力': 432,
 '煞車': 982,
 '功能': 421,
 '方向盤': 845,
 '喜歡': 493,
 '每個': 924,
 '機會': 911,
 '尤其': 624,
 '一個月': 184,
 '幾次': 658,
 '版上': 989,
 '搜尋': 802,
 '山路': 633,
 '四輪': 500,
 '還能': 1390,
 '好好': 570,
 '願意': 1479,
 '重點': 1406,
 '表示': 1187,
 '回家': 506,
 '早上': 855,
 '